name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

      - name: Build
        run: make build

      - name: Run tests
        run: make test

      - name: Run test coverage
        run: make cover

      - name: Clean
        run: make clean
